dist: xenial
sudo: required

notifications:
  email: false

language: python
cache: pip

matrix:
  include:
  - python: 3.5
  - python: 3.6
  - python: 3.7
  - python: 3.8

install:
# Install latest ghostscript from binary on https://www.ghostscript.com/download/gsdnld.html
- wget https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs927/ghostscript-9.27-linux-x86_64.tgz
- tar xvf ghostscript-9.27-linux-x86_64.tgz
- sudo mv ghostscript-9.27-linux-x86_64/gs-927-linux-x86_64 /usr/bin/gs
- pip install tox-travis

script: tox
