dist: xenial
sudo: required

notifications:
  email: false

language: python
cache: pip

matrix:
  include:
  - python: 3.5
  - python: 3.6
  - python: 3.7

install:
- sudo apt-get install ghostscript
- pip install tox-travis

script: tox
